<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-HOME" failures="1" tests="1" name="Test(failed)" time="3.613" errors="0" timestamp="2023-03-10T00:27:17 IST">
  <testcase classname="com.CMS.TestCases.LoginPageTestCases" name="forgetPasswordTest" time="0.616">
    <failure type="java.lang.AssertionError" message="expected [Enter your Login ID to receive your password in mail.User Name] but found [Enter your Login ID to receive your password in mail.
User Name]">
      <![CDATA[java.lang.AssertionError: expected [Enter your Login ID to receive your password in mail.User Name] but found [Enter your Login ID to receive your password in mail.
User Name]
at com.CMS.TestCases.LoginPageTestCases.forgetPasswordTest(LoginPageTestCases.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- forgetPasswordTest -->
  <testcase classname="com.CMS.TestCases.LoginPageTestCases" name="successfulLoginTest" time="0.0">
    <ignored/>
  </testcase> <!-- successfulLoginTest -->
</testsuite> <!-- Test(failed) -->
